import pandas as pd
import streamlit as st

from banksense_ai.predict import predict_risk


st.set_page_config(
    page_title="BankSense AI",
    page_icon="🏦",
    layout="centered",
)


st.title("BankSense AI")
st.subheader("Banking Customer Risk Analysis")

st.write(
    "Enter customer information to estimate the probability that the "
    "customer belongs to the high-risk class."
)

st.divider()


st.header("Customer Information")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input(
        "Age",
        min_value=18,
        max_value=100,
        value=35,
        step=1,
    )

    annual_income = st.number_input(
    "Annual Income",
    min_value=0.0,
    value=75000.0,
    step=1000.0,
)

    st.caption(
    "Enter annual income using the currency applicable to the selected country."
)

    customer_tenure_years = st.number_input(
    "Customer Tenure (Years)",
    min_value=0,
    max_value=11,
    value=6,
    step=1,
)

    st.caption(
    "Maximum supported customer tenure: 11 years."
)

    gender = st.selectbox(
        "Gender",
        ["Female", "Male", "Non-binary"],
    )

with col2:
    country = st.selectbox(
        "Country",
        [
            "Australia",
            "Canada",
            "France",
            "Germany",
            "India",
            "Japan",
            "Netherlands",
            "New Zealand",
            "Norway",
            "Singapore",
            "South Korea",
            "Sweden",
            "Switzerland",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
        ],
    )

    occupation = st.selectbox(
        "Occupation",
        [
            "Architect",
            "Business Owner",
            "Consultant",
            "Data Analyst",
            "Doctor",
            "Engineer",
            "Financial Analyst",
            "Lawyer",
            "Manager",
            "Nurse",
            "Researcher",
            "Sales Professional",
            "Software Engineer",
            "Student",
            "Teacher",
            "Unknown",
        ],
    )

    employment_status = st.selectbox(
        "Employment Status",
        [
            "Employed",
            "Retired",
            "Self-employed",
            "Student",
            "Unemployed",
        ],
    )


st.divider()


if st.button("Assess Risk", type="primary", use_container_width=True):

    customer = pd.DataFrame(
        [
            {
                "age": age,
                "annual_income": annual_income,
                "customer_tenure_years": customer_tenure_years,
                "gender": gender,
                "country": country,
                "occupation": occupation,
                "employment_status": employment_status,
            }
        ]
    )

    try:
        result = predict_risk(customer)

        prediction = int(result.loc[0, "high_risk_prediction"])
        probability = float(result.loc[0, "high_risk_probability"])

        st.divider()
        st.header("Risk Assessment")

        col1, col2 = st.columns(2)

        with col1:
            if prediction == 1:
                st.error("High-Risk Prediction")
            else:
                st.success("Low-Risk Prediction")

        with col2:
            st.metric(
                "High-Risk Probability",
                f"{probability:.2%}",
            )

        st.progress(probability)

        st.caption(
            "This prediction is generated by the BankSense AI machine "
            "learning model and should not be treated as a definitive "
            "financial or credit decision."
        )

    except Exception as error:
        st.error(f"Prediction failed: {error}")